[book]
authors = ["Hedayat Abedijoo"]
language = "en"
multilingual = false
src = "src"
title = "Design Patterns in Rust"

[output.html.fold]
enable = true
level = 1


[output.html]
additional-css = ["./styles.css"]