[book]
authors = ["Hedayat Abedijoo"]
language = "en"
multilingual = false
src = "src"
title = "Design Patterns in Rust"

[output.html.fold]
enable = true
level = 1


[output.html]
additional-css = ["./styles.css"]
curly-quotes = true
default-theme = "rust"
git-repository-url = "https://github.com/HedayatAbedijoo/design-patterns-in-rust"
git-repository-icon = "fa-github"

[build]
build-dir = "docs"
